export const A11yLabel = {
  normalLabel: '{{label}} Label {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  mediaLabel: '{{label}} Label with {{labelType}} {{shortDescription}}, Label {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  normalDropZone: '{{mark}} {{label}} in drop zone {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  groupNormalDropZone: '{{mark}} {{label}} in {{groupTitle}} group {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  mediaDropZone: '{{label}} {{mark}} Label with {{labelType}} {{shortDescription}}, in drop zone {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  groupMediaDropZone: '{{label}} {{mark}} Label with {{labelType}} {{shortDescription}}, in {{groupTitle}} group {{currentIndex}} of {{totalLabelLength}}. {{labelDynamicText}}',
  normalLabelLift: 'Label {{label}} lifted. Press left right arrows to move between drop zone lists, space bar to drop, and escape to cancel.',
  normalLabelLiftMouse: 'Label {{label}} lifted. Drag to move between drop zone lists.',
  groupNormalLabelLift: 'Label {{label}} lifted. Press left right arrows to move between groups, space bar to drop, and escape to cancel.',
  groupNormalLabelLiftMouse: 'Label {{label}} lifted. Drag to move between groups.',
  mediaLabelLift: '{{label}} Label with {{labelType}} {{shortDescription}} lifted. Press left right arrows to move between drop zone lists, space bar to drop, and escape to cancel.',
  mediaLabelLiftMouse: '{{label}} Label with {{labelType}} {{shortDescription}} lifted. Drag to move between drop zone lists.',
  groupMediaLabelLift: '{{label}} Label with {{labelType}} {{shortDescription}} lifted. Press left right arrows to move between groups, space bar to drop, and escape to cancel.',
  groupMediaLabelLiftMouse: '{{label}} Label with {{labelType}} {{shortDescription}} lifted. Drag to move between groups.',
  dropZoneMove: '{{description}} Drop zone {{currentIndex}} of {{totalDropZoneLength}} {{dockText}}, space bar to drop, and escape to cancel.',
  dropZoneMoveMouse: '{{description}} Drop zone {{currentIndex}} of {{totalDropZoneLength}}.',
  groupDropZoneMove: '{{groupTitle}} {{shortDescription}}, Group {{currentIndex}} of {{totalDropZoneLength}} {{dockText}}, space bar to drop, and escape to cancel.',
  groupDropZoneMoveMouse: '{{groupTitle}} {{shortDescription}}, Group {{currentIndex}} of {{totalDropZoneLength}}.',
  labelMoveBackToList: 'Labels list, space bar to drop, and escape to cancel.',
  normalLabelDropped: 'Label {{label}} dropped in drop zone {{currentIndex}} of {{totalDropZoneLength}}.',
  groupNormalLabelDropped: 'Label {{label}} dropped in {{groupTitle}}.',
  mediaLabelDropped: '{{label}} Label with {{labelType}}  {{shortDescription}} dropped in drop zone {{currentIndex}} of {{totalDropZoneLength}}.',
  groupMediaLabelDropped: '{{label}} Label with {{labelType}} {{shortDescription}} dropped in {{groupTitle}}.',
  labelDroppedToList: 'Dropped in the Labels list',
  labelImageDescription: '{{labelText}} Image {{imageIndex}} description opens in a modal',
  groupImageDescription: '{{groupTitle}} {{shortDescription}} Image description opens in a modal',
  notes: 'Notes for {{text}}',
  feedback: 'Feedback for {{text}}',
  labelKeyboardInteraction: 'Press space bar to lift the Label',
  IncorrectEmptyDropzone: '{{incorrectValue}} {{dropzoneDescription}} Drop zone {{currentIndex}} of {{totalDropZoneLength}}.',
  cancelMovementLabel: 'Movement canceled. Label dropped in Labels list',
  cancelMovementDropZone: 'Movement cancelled. Label dropped in drop zone {{currentIndex}} of {{totalDropZoneLength}}',
  groupCancelMovementDropZone: 'Movement cancelled. Label dropped in {{groupTitle}}.',
  resetLabel: 'All labels returned to their original location.',
  undoLabel: 'Movement undone.',
  turnOffBrowseMode: 'Turn off browse mode or the virtual cursor to select the label.',
  reviewModeText: 'Kindly turn off Virtual cursor/Browse mode to review the work.',
  emptyDropZone: 'Empty drop zone {{currentIndex}} of {{docksLength}} {{dropzoneDescription}}'
};
