export const APP_CONFIG = {
  MIN_CANVAS_WIDTH: 800,
  MIN_CANVAS_HEIGHT: 600,
  APP_BORDER: 2,
  HEADER_ELE_HEIGHT: 45,
  RULER_ELE: 27,
  TOOL_ELE_WIDTH: 360,
  LABEL_ELE_WIDTH: 226,
  HEADER_ELE_HEIGHT_TEST: 49,
  SKIP_LINK_HEIGHT: 40,
  LABEL_OPTIONS: {
    EDIT: 'Edit',
    ADD_LABEL_BELOW: 'Add Label Below',
    MARK_AS_DISTRACTOR: 'Mark as Distractor',
    ADD_DROPZONE: 'Add Drop zone',
    DELETE: 'Delete',
    MARK_AS_LABEL: 'Mark as Label'
  },
  NEW_LABEL_OPTIONS: {
    EDIT: 'Edit',
    ADD_LABEL_BELOW: 'Add Label Below',
    MARK_AS_DISTRACTOR: 'Mark as Distractor', 
    DELETE: 'Delete',
  },
  DISTRACTOR_OPTIONS: {
    EDIT: 'Edit',
    ADD_LABEL_BELOW: 'Add Label Below',
    MARK_AS_LABEL: 'Mark as Label',
    DELETE: 'Delete',
  },
  DROPZONE_CORDINATES: {
    INITIAL_X_AXIS: 404,
    INITIAL_Y_AXIS: 20,
    X_AXIS: 0,
    Y_AXIS: 100,
  },
  LABEL_OPTIONS_SAME_LABEL_TO_MULTIPLE_DOCK: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 2, viewValue: 'Mark as Distractor' },
    { value: 4, viewValue: 'Add Drop zone' },
    { value: 3, viewValue: 'Delete' },
  ],
  LABEL_OPTIONS_SAME_LABEL_TO_SAME_DOCK: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 2, viewValue: 'Mark as Distractor' },
    { value: 3, viewValue: 'Delete' },
  ],
  DISTRACTOR_OPTIONS_BOTH_CASE: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 3, viewValue: 'Delete' },
  ],
  DISTRACTOR_OPTIONS_BOTH_CASE_WITH_IMAGE: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 2, viewValue: 'Delete' },
  ],
  LABEL_OPTIONS_SAME_LABEL_TO_MULTIPLE_DOCK_WITH_IMAGE: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 2, viewValue: 'Mark as Distractor' },
    { value: 4, viewValue: 'Add Drop zone' },
    { value: 3, viewValue: 'Delete' },
  ],
  LABEL_OPTIONS_SAME_LABEL_TO_SAME_DOCK_WITH_IMAGE: [
    { value: 0, viewValue: 'Edit' },
    { value: 1, viewValue: 'Add Label Below' },
    { value: 2, viewValue: 'Mark as Distractor' },
    { value: 3, viewValue: 'Delete' },
  ],
  DELETE_LABEL_IN_KEBAL: { value: 3, viewValue: 'Delete' },
  MODAL_POPUP_MESSAGE_ON_DELETE_FOR_LABEL:
    'Are you sure you want to delete the selected Label? Deleting the label will remove the corresponding dock as well.',
  MODAL_POPUP_MESSAGE_ON_DELETE_FOR_DISTRACTOR: 'Are you sure you want to delete the selected Distractor?',
  MODAL_POPUP_MESSAGE_ON_DELETE_FOR_LABEL_FOR_GROUPING: 'Are you sure you want to delete selected label?',
  CORDINATES_FOR_IMAGE_BOUNDARY: {
    X_LEFT: 0,
    X_RIGHT: 400,
    Y_TOP: 0,
    Y_BOTTOM: 600,
  },
  DEFAULT_POSITION_CORDINATE_FOR_OVERLAPPING_DOCK: 420,
  DELETE_CONFIRMATION_LABEL: 'Delete Confirmation for Label',
  DELETE_CONFIRMATION_DISTRACTOR: 'Delete Confirmation for Distractor',
  NEW_DOCK_WIDTH: 150,
  NEW_DOCK_HEIGHT: 60,
  NEW_DOCK_INITIAL_LINE: 20,
  NEW_DOCK_SEPARATION_GAP: 20,
  NEW_DOCK_RIGHT_WIDTH_INCREASE: 200,
  DOCK_VALUE_TO_TRAVERSE_WITH: 1,
  UNDO_LIMIT: 50,
  MAX_BACKGROUND_IMAGE_WIDTH_ALLOWED: 250,
  MAX_BACKGROUND_IMAGE_HEIGHT_ALLOWED: 250,
  DEFAULT_CANVAS_WIDTH: 900,
  DEFAULT_CANVAS_HEIGHT: 600,
  DEFAULT_IMAGE_WIDTH_GROUPING: 180,
  DEFAULT_IMAGE_HEIGHT_GROUPING: 220,
  MIN_MAGNIFY_WIDTH: 200,
  MAX_MAGNIFY_WIDTH: 300,
  MIN_MAGNIFY_HEIGHT: 200,
  MAX_MAGNIFY_HEIGHT: 300,
  IMAGE_GROUPING_MARGIN: 2, // its in percentage.
  MAXIMUM_WIDTH_ALLOWED_IMAGE_GROUPING: 100,
  MAXIMUM_HEIGHT_ALLOWED_IMAGE_GROUPING: 100,
  GROUP_EDITOR_PLACEHOLDER: 'Enter Group Title',
  DROPZONE_EDITOR_PLACEHOLDER: 'Enter Description',
  FEEDBACK_EDITOR_PLACEHOLDER: 'Enter Feedback',
  LABEL_EDITOR_PLACEHOLDER: 'Enter Label',
  NOTE_EDITOR_PLACEHOLDER: 'Enter Note',
  ACTIVITY_TYPE_TEXT_COMPLETION_ORDERING:
    'This activity type is not supported in Complaint Click Drag . Create a new answer object to start from scratch.',
  ACTIVITY_CONTAINS_MORE_THAN_20_LABELS:
    'Complaint Click Drag supports a maximum of 20 labels. Only the first 20 labels will be retained. Do you wish to proceed?',
  ACTIVITY_CONTAINS_MORE_THAN_1_BG_IMAGE: 'More than one background image is not supported in Complaint Click Drag.',
  TEXT_CREATED_USING_TYPE_TOOL:
    'Complaint Click Drag does not support Type tool, any text created using Type tool will be ignored.',
  ACTIVITY_HAVING_MORE_THAN_20_LABELS_AND_TYPE_TOOL: `Complaint Click Drag does not support Type tool, any text created using Type tool will be ignored.
  Complaint Click Drag supports a maximum of 20 labels.Only the first 20 labels will be retained.Do you wish to proceed?`,
  ACTIVITY_HAVING_MORE_GROUP_IMG: `Single image used across multiple drop zones is not supported in Complaint Click Drag. Click "OK" to start building new activity from scratch.`,
  NO_IMAGE_MEDIA: 'No images available. Please use Media tab to upload/select images for this exercise',
};
